import {frameAt,timing,keyframes,describe,codeFor,voltageFor,ROWS,COLS,type Snapshot,type Shutter} from './readout';
export interface ReadoutController {tick:(dt:number)=>void;setActive:(active:boolean)=>void;seekRow:(row:number)=>void;getState:()=>Snapshot;}
export function mountReadout(onState:(state:Snapshot)=>void):ReadoutController{
 const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 let shutter:Shutter='rolling',exposure=4,time=0,speed=1,playing=false,active=false;
 const top=get('readout-controls'),bottom=get('readout-analysis'),detail=get('readout-detail');
 top.innerHTML=`<div class="shutter-switch" role="group" aria-label="셔터 방식"><button data-shutter="rolling" aria-pressed="true">롤링 셔터</button><button data-shutter="global" aria-pressed="false">글로벌 셔터</button></div><div class="readout-buttons"><button id="readout-play">▶ 재생</button><button id="readout-back" aria-label="이전 동작">이전 단계</button><button id="readout-next">다음 단계</button><button id="readout-restart">처음부터</button><label>속도 <select id="readout-speed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><label>노출 <select id="readout-exposure"><option value="2">2 Tline</option><option value="4" selected>4 Tline</option><option value="8">8 Tline</option></select></label></div><div class="readout-clock"><label for="readout-time">시간 탐색</label><output id="readout-clock"></output></div><input id="readout-time" type="range" min="0" max="12" step="0.001" value="0"><div class="readout-legend"><span class="lg-reset">행 제어</span><span class="lg-expose">노출</span><span class="lg-memory">MEM 저장</span><span class="lg-analog">열 전압</span><span class="lg-digital">디지털 출력</span></div>`;
 bottom.innerHTML=`<div class="readout-phase"><span id="readout-row">준비</span><strong id="readout-title"></strong><span id="readout-complete"></span></div><div class="adc-heading"><strong>열 ADC 뱅크</strong><span id="adc-ramp"></span></div><div id="adc-cells">${Array.from({length:COLS},(_,c)=>`<div class="adc-cell" id="adc-${c}"><span>C${c+1}</span><strong>—</strong><small>대기</small></div>`).join('')}</div><p class="readout-caption">8개 대표 열 · 8비트 단일 경사 ADC 예시 · 실제 센서의 해상도/구조와 다를 수 있음</p><div class="timing-heading"><strong>행별 노출 창 비교</strong><span>행을 누르면 해당 행 읽기로 이동</span></div><div class="timing-comparison">${(['rolling','global'] as const).map(m=>`<section class="timing-chart" id="chart-${m}"><h3>${m==='rolling'?'롤링: 행마다 시간차':'글로벌: 같은 노출 창'}</h3>${Array.from({length:ROWS},(_,r)=>`<button class="timing-row" data-timing-mode="${m}" data-timing-row="${r}"><span>R${r+1}</span><div class="timing-track"><i class="timing-exposure"></i><i class="timing-memory"></i><i class="timing-read"></i><b class="timing-cursor"></b></div></button>`).join('')}</section>`).join('')}</div><p class="readout-caption">초록 = 노출 · 보라 = 저장 대기 · 파랑 = 행 읽기. 1 Tline은 이 예시의 한 행 읽기 슬롯입니다.</p>`;
 detail.innerHTML=`<div class="eyebrow">SHUTTER & READOUT LAB</div><h2 id="readout-mode-name"></h2><p id="readout-summary"></p><div class="readout-explanation"><strong id="readout-detail-title"></strong><p id="readout-explanation"></p></div><div id="readout-control-state"></div><div class="control-signals"><span id="signal-sel">SEL</span><span id="signal-rst">FD RST</span><span id="signal-tx">TX</span><span id="signal-global">GLOBAL TX</span></div><div class="pixel-route" id="pixel-route"></div><section class="cds-example"><h3>선택 행의 C4 신호</h3><dl><dt>FD 기준 Vreset</dt><dd id="cds-ref">—</dd><dt>신호 Vsignal</dt><dd id="cds-signal">—</dd><dt>CDS 차이</dt><dd id="cds-diff">—</dd><dt>최종 8비트 코드</dt><dd id="cds-code">—</dd></dl><p>이 예시의 부호: Vreset − Vsignal<br>ADC 입력 범위 0–1 V · 수치는 교육용</p></section><section class="readout-frame"><h3>외부로 읽은 프레임</h3><div id="frame-grid" aria-label="출력이 완료된 행의 픽셀 코드">${Array.from({length:ROWS},(_,r)=>`<div><span>R${r+1}</span>${Array.from({length:COLS},(_,c)=>`<span id="frame-${r}-${c}">·</span>`).join('')}</div>`).join('')}</div></section><details class="readout-assumptions"><summary>이 애니메이션의 범위와 근거</summary><p>글로벌은 PD → 차광 전하 저장 노드(MEM) → FD를 사용하는 전하 저장형 예시입니다. FD는 전하를 전압으로 바꾸고, SF(소스 팔로어)가 열 배선을 구동합니다. 모든 글로벌 셔터가 같은 픽셀이나 CDS 구조를 쓰지는 않습니다.</p><p>글로벌 리셋만 동시에 하고 노출 종료는 행별로 하는 GRR 모드와는 다릅니다. BSI/적층 구조 자체가 글로벌 셔터를 뜻하지도 않습니다.</p><p>한 프레임, 8개 행, 8개 대표 열, 단일 경사 ADC로 단순화했습니다. 실제 지연·전압·TX 파형·ADC 공유 비율·다중 레인 출력·다음 프레임과 겹치는 동작은 재현하지 않습니다. 노출 길이는 오른쪽의 기존 밝기 실험과 독립적인 Tline 단위입니다.</p><a href="https://www.sony.com/en/SonyInfo/News/Press/201903/19-023E/" target="_blank" rel="noreferrer">Sony: 글로벌 셔터 전하 저장 ↗</a><a href="https://andor.oxinst.com/manuals/cameras/zl41-cell/features/rolling_and_global_shutter_mechanisms.htm" target="_blank" rel="noreferrer">Andor: 롤링 셔터 읽기·CDS 순서 ↗</a></details>`;
 function paint(){
  const s=frameAt(shutter,exposure,time),d=describe(s);time=s.time;top.dataset.phase=s.phase;top.dataset.shutter=shutter;top.dataset.activeRow=String(s.activeRow??-1);
  get('readout-mode-name').textContent=shutter==='rolling'?'롤링 셔터':'글로벌 셔터 · 전하 저장형';
  get('readout-summary').textContent=shutter==='rolling'?'행별 노출 시작과 종료가 순차적으로 이동합니다. 행 리셋과 다른 행의 읽기가 겹칠 수 있습니다.':'노출 종료는 전체 픽셀이 동시에, 저장한 신호의 읽기는 행별 순서대로 진행됩니다.';
  get('readout-play').textContent=playing?'Ⅱ 일시정지':s.phase==='done'?'▶ 다시 재생':'▶ 재생';get('readout-play').setAttribute('aria-pressed',String(playing));
  document.querySelectorAll<HTMLElement>('button[data-shutter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shutter===shutter)));
  get<HTMLInputElement>('readout-time').max=String(s.duration);get<HTMLInputElement>('readout-time').value=String(time);get('readout-clock').textContent=`${time.toFixed(2)} / ${s.duration.toFixed(2)} Tline`;
  get('readout-row').textContent=s.activeRow===null?s.globalTransfer?'전체 픽셀':s.phase==='done'?'완료':'노출 준비 / 진행':`선택 행 R${s.activeRow+1}`;
  get('readout-title').textContent=d.title;get('readout-detail-title').textContent=d.title;get('readout-explanation').textContent=d.text;get('readout-complete').textContent=`${s.completed} / 8행 출력`;
  const resets=s.activeRow!==null&&s.resetRows.length?` · 동시에 PD 리셋: ${s.resetRows.map(r=>'R'+(r+1)).join(', ')}`:'';get('readout-control-state').textContent=d.control+resets;
  const selected=['reference','transfer','cds'].includes(s.phase);get('signal-sel').classList.toggle('on',selected);get('signal-rst').classList.toggle('on',s.phase==='reference'&&s.progress<.4);get('signal-tx').classList.toggle('on',s.phase==='transfer');get('signal-global').classList.toggle('on',s.globalTransfer);
  const route=shutter==='global'?['PD','MEM','FD / SF','열 배선','CDS','ADC','출력']:['PD','FD / SF','열 배선','CDS','ADC','출력'];
  const hot=s.phase==='store'?'MEM':s.phase==='transfer'||s.phase==='reference'?'FD / SF':s.phase==='cds'?'CDS':s.phase==='adc'?'ADC':s.phase==='output'?'출력':'PD';get('pixel-route').innerHTML=route.map(n=>`<span class="${n===hot?'active':''}">${n}</span>`).join('<b>→</b>');
  get('adc-ramp').textContent=s.phase==='adc'?`RAMP ${(s.counter/255).toFixed(3)} V · COUNT ${s.counter} / 255`:s.phase==='output'?'열 래치 → 출력 경로':'입력 샘플 대기';
  for(let c=0;c<COLS;c++){const cell=get('adc-'+c);cell.classList.toggle('latched',!!s.latched[c]);cell.querySelector('strong')!.textContent=s.latched[c]?String(s.codes[c]):s.phase==='adc'?String(s.counter):'—';cell.querySelector('small')!.textContent=s.latched[c]?'래치 완료':s.phase==='adc'?'비교 중':'대기';}
  const row=s.activeRow,resetSample=row!==null&&(['transfer','cds','adc','output'].includes(s.phase)||s.phase==='reference'&&s.progress>=.4),signalSample=row!==null&&['cds','adc','output'].includes(s.phase),voltage=row===null?0:voltageFor(row,3,exposure);
  get('cds-ref').textContent=resetSample?'1.200 V':'—';get('cds-signal').textContent=signalSample?(1.2-voltage).toFixed(3)+' V':'—';get('cds-diff').textContent=signalSample?voltage.toFixed(3)+' V':'—';get('cds-code').textContent=s.latched[3]?String(s.codes[3]):'—';
  for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const cell=get(`frame-${r}-${c}`);cell.textContent=s.rows[r].complete?String(codeFor(r,c,exposure)):'·';cell.classList.toggle('complete',s.rows[r].complete);}
  const scale=Math.max(frameAt('rolling',exposure,0).duration,frameAt('global',exposure,0).duration);
  document.querySelectorAll<HTMLElement>('[data-timing-row]').forEach(b=>{const kind=b.dataset.timingMode as Shutter,r=Number(b.dataset.timingRow),t=timing(kind,exposure,r);const exp=b.querySelector<HTMLElement>('.timing-exposure')!,mem=b.querySelector<HTMLElement>('.timing-memory')!,read=b.querySelector<HTMLElement>('.timing-read')!,cursor=b.querySelector<HTMLElement>('.timing-cursor')!;exp.style.left=`${t.start/scale*100}%`;exp.style.width=`${exposure/scale*100}%`;mem.style.left=`${t.end/scale*100}%`;mem.style.width=`${kind==='global'?(t.readStart+.2-t.end)/scale*100:0}%`;read.style.left=`${t.readStart/scale*100}%`;read.style.width=`${1/scale*100}%`;cursor.style.left=`${time/scale*100}%`;cursor.hidden=kind!==shutter;b.classList.toggle('active',kind===shutter&&s.activeRow===r);b.setAttribute('aria-label',`${kind==='rolling'?'롤링':'글로벌'} R${r+1} 읽기로 이동`);});
  onState(s);
 }
 function seek(value:number){playing=false;time=value;paint();}
 get('readout-play').onclick=()=>{if(frameAt(shutter,exposure,time).phase==='done')time=0;playing=!playing;paint();};
 get('readout-restart').onclick=()=>seek(0);
 get('readout-time').oninput=()=>seek(Number(get<HTMLInputElement>('readout-time').value));
 get('readout-speed').onchange=()=>{speed=Number(get<HTMLSelectElement>('readout-speed').value);};
 get('readout-exposure').onchange=()=>{exposure=Number(get<HTMLSelectElement>('readout-exposure').value);seek(0);};
 document.querySelectorAll<HTMLElement>('button[data-shutter]').forEach(b=>b.onclick=()=>{shutter=b.dataset.shutter as Shutter;seek(0);});
 get('readout-next').onclick=()=>{const s=frameAt(shutter,exposure,time);seek(Math.min(s.duration,(keyframes(shutter,exposure).find(t=>t>time+.002)??s.duration)+.001));};
 get('readout-back').onclick=()=>{const points=keyframes(shutter,exposure).filter(t=>t<time-.002);seek(points.length?points.at(-1)!+.001:0);};
 document.querySelectorAll<HTMLElement>('[data-timing-row]').forEach(b=>b.onclick=()=>{shutter=b.dataset.timingMode as Shutter;seek(timing(shutter,exposure,Number(b.dataset.timingRow)).readStart+.001);});
 paint();return {tick(dt){if(!active||!playing)return;time+=dt*speed;const s=frameAt(shutter,exposure,time);if(s.phase==='done')playing=false;paint();},setActive(value){active=value;if(!value)playing=false;paint();},seekRow(row){if(Number.isInteger(row)&&row>=0&&row<ROWS)seek(timing(shutter,exposure,row).readStart+.001);},getState(){return frameAt(shutter,exposure,time);}};
}
